### PR TITLE
reduced app info image sizes <500kb

### PR DESCRIPTION
**Pull request by J-C-B**

### CODE REVIEW

**Comment by UgaitzEtxebarria** [comment]
The resolution of images must be 1920x1080, we need to resize it without lose the resolution. 

I tried to use some websites like https://www.reduceimages.com to reduce the size and they trim the bits, and we need to be 24.

Particularly i dont know how we can reduce the size without change the resolution or the bits... If we dont find any option maybe the reduction of bits is the most affordable option

**Comment by J-C-B** [comment]
i cant see a 500kb limit in thier docs? where did you find that requirment? - https://developer.samsung.com/smarttv/design/app-icons-and-screenshots.html#App-Screenshot

they do have a 300kb limif for app icons though

**Comment by UgaitzEtxebarria** [comment]
[Here](https://developer.samsung.com/tv-seller-office/application-publication-process.html) is a summary of the process and adds more requirements, I don't know if then have forgotten to add it on the other page.
About the image size of the icon, it is controlled, all icon has less than 300kb. This requirement was added in the readme which is on App Icon folder

**Comment by J-C-B** [comment]
hi, no it isn't - take a look at the table on the link you sent - it shows JPG as the format
https://developer.samsung.com/tv-seller-office/application-publication-process.html

|Application package | Dimensions | Format | Maximum Size | 
|----------------|--------|--------|--------|
|Application screenshot image | 1280x720 px or 1920x1080 px | JPG | 500 kB |

**Pull request merged**
